server {
    listen 80;
    server_name <GRAFANA_HOST>;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name <GRAFANA_HOST>;

    ssl_certificate     /etc/ssl/certs/<GRAFANA_HOST>.crt;
    ssl_certificate_key /etc/ssl/private/<GRAFANA_HOST>.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
